# Generated by Django 6.1.1 on 2026-09-22 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hosts', '0002_alter_host_hostname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chequeo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField()),
                ('estado', models.CharField(choices=[('up', 'Up'), ('down', 'Down'), ('timeout', 'Timeout')], max_length=7)),
                ('tiempo_respuesta_ms', models.IntegerField()),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hosts.host')),
            ],
        ),
    ]
