# Generated by Django 6.1.1 on 2026-09-22 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network_checks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(choices=[('warning', 'Warning'), ('critical', 'Critical')], max_length=8)),
                ('mensaje', models.TextField()),
                ('resuelta', models.BooleanField()),
                ('fecha_creacion', models.DateTimeField()),
                ('chequeo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network_checks.chequeo')),
            ],
        ),
    ]
