# Generated by Django 6.1.1 on 2026-09-21 22:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('hostname', models.CharField(max_length=64)),
                ('ip_address', models.GenericIPAddressField(protocol='IPv4', unique=True)),
                ('puerto', models.IntegerField()),
                ('intervalo_chequeo', models.TimeField()),
                ('activo', models.BooleanField(default=True)),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
