# Generated by Django 6.1.1 on 2026-09-23 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='tipo_servicio',
            field=models.CharField(choices=[('base_datos', 'Base de Datos'), ('api', 'API'), ('custom', 'Otro')], max_length=13),
        ),
    ]
