# Generated by Django 6.1.1 on 2026-09-22 20:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='hostname',
            field=models.CharField(max_length=63, validators=[django.core.validators.RegexValidator(regex='^[A-Za-z][A-Za-z0-9-]{0,61}[A-Za-z0-9]$')]),
        ),
    ]
